### ISSUE TITLE
Applied Energistics 2 - Server disconnection

### ISSUE THREAD

**Issue by Spads** [Granik24/tekkit#1]
Depositing any item manually (without shift-click) will cause a server disconnection (Game error) most of the time. This occurs with all ME terminal variants.

**Comment by Granik24** [comment]
Do you have any crash reports or something from log?

**Comment by Spads** [comment]
Great!

**Comment by Granik24** [comment]
It looks like serious bug in new build 22. In next version, downgrading to build 18. Thank you for your report!
