### ISSUE TITLE
Version 1.3.3-fix download error

### ISSUE THREAD

**Issue by Spads** [Granik24/tekkit#4]
"Error unzipping a file for the following pack: Tekkit Classic on 1.7.10
Attempting to extract file tekitclassis-1.3.3-fix.zip, but it did not exist.
Please consult the modpack author"

**Comment by Granik24** [comment]
Try to reinstall pack in "Modpack Options" 
We have solder, so we don't have any "tekitclassis-1.3.3-fix.zip"

**Comment by Spads** [comment]
I tried that but it didn't seem to have an effect.

**Comment by Granik24** [comment]
I'm sorry, we have some issues with our MySQL server. Working on fix it!

**Comment by Spads** [comment]
Hahah np thanks!

**Comment by Granik24** [comment]
Everythink is online. Restart your launcher and enjoy playing! :)

**Comment by Spads** [comment]
Yap, seems all good now :)

**Comment by Granik24** [comment]
:+1:
